// <auto-generated />
namespace Slack.Identity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class appuser15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appuser15));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041526067_appuser1.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
