// <auto-generated />
namespace Slack.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class context11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(context11));
        
        string IMigrationMetadata.Id
        {
            get { return "201805161431359_context1.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
